font_family Iosevka
font_size 12.000000

shell_integration no-rc

allow_remote_control yes
background #101010
background_opacity 1
confirm_os_window_close 0
dynamic_background_opacity no
enable_audio_bell no
scrollback_lines 10000
window_padding_width 2


map SUPER+t new_os_window_with_cwd
map ctrl+shift+, load_config_file
map ctrl+shift+f none
map ctrl+t none
map ctrl+w none
